.gitignore, build.gradle, src/main/java/com/jisungin/JisunginApplication.java, src/main/java/com/jisungin/api/oauth/OauthController.java, src/main/java/com/jisungin/api/oauth/OauthTypeConverter.java, src/main/java/com/jisungin/application/oauth/OauthService.java, src/main/java/com/jisungin/config/WebConfig.java, src/main/java/com/jisungin/domain/oauth/OauthId.java, src/main/java/com/jisungin/domain/oauth/OauthType.java, src/main/java/com/jisungin/domain/oauth/authcode/AuthCodeRequestUrlProvider.java, src/main/java/com/jisungin/domain/oauth/authcode/AuthCodeRequestUrlProviderComposite.java, src/main/java/com/jisungin/domain/oauth/client/UserClient.java, src/main/java/com/jisungin/domain/oauth/client/UserClientComposite.java, src/main/java/com/jisungin/domain/user/User.java, src/main/java/com/jisungin/domain/user/repository/UserRepository.java, src/main/java/com/jisungin/exception/ErrorCode.java, src/main/java/com/jisungin/infra/oauth/authcode/KakaoAuthCodeRequestUrlProvider.java, src/main/java/com/jisungin/infra/oauth/config/HttpInterfaceConfig.java, src/main/java/com/jisungin/infra/oauth/kakao/KakaoOauthConfig.java, src/main/java/com/jisungin/infra/oauth/kakao/KakaoUserClient.java, src/main/java/com/jisungin/infra/oauth/kakao/client/KakaoApiClient.java, src/main/java/com/jisungin/infra/oauth/kakao/dto/KakaoToken.java, src/main/java/com/jisungin/infra/oauth/kakao/dto/KakaoUserResponse.java, src/main/resources/application.yml
close #1  
- 소셜 로그인 요청 시 해당 서비스 로그인 화면으로 Redirect 하는 기능 구현
- 현재는 카카오만 가능
- 프론트단에서 넘겨주는 인증 코드로 AccessToken을 발급 받는 기능 구현
- AccessToken으로 사용자 정보를 가져와서 회원가입 / 로그인 가능
안녕하세요 ~ 소셜 로그인 관련 첫 PR입니다.
처음에는 스프링 시큐리티를 사용해서 구현하려고 했지만 의존도가 높아지는 것 같아 시큐리티 없이 구현했습니다.
결과적으론 시큐리티에 대한 의존성은 없어졌지만 로직 자체는 조금 복잡해진 것 같습니다.
일단 프론트단에서 사용자가 로그인 & 정보 제공 동의를 완료하면 인증 서버가 프론트단한테 인증 코드를 보내는 부분이 4번 과정입니다.
4번 Redirect 과정에서 인증 코드를 꺼내서 서버에 인증 코드와 함께  POST 요청을 해야 로직이 수행됩니다.
제가 구현한 부분은 4번 중간부터 구현했다고 보시면 될 거 같습니다.
코드에서 궁금한 점이나 피드백 있으시면 편하게 달아주세요.
또한 블로그 글을 작성했으니 참고하시고 질문 달아주셔도 좋을 것 같아요 👍 
🔥  https://trysolve.tistory.com/25 🔥
=> [Feature] 소셜 로그인 구현

src/main/java/com/jisungin/api/talkroom/TalkRoomController.java, src/main/java/com/jisungin/api/talkroom/request/TalkRoomEditRequest.java, src/main/java/com/jisungin/application/talkroom/TalkRoomService.java, src/main/java/com/jisungin/application/talkroom/request/TalkRoomEditServiceRequest.java, src/main/java/com/jisungin/domain/talkroom/TalkRoom.java, src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepository.java, src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRoleRepository.java, src/main/java/com/jisungin/domain/user/User.java, src/main/java/com/jisungin/exception/ErrorCode.java, src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java, src/test/java/com/jisungin/application/service/talkroom/TalkRoomServiceTest.java
close #8
* TalkRoom 수정 API 구현
* TalkRoom 수정 API 테스트 코드 작성
```java
public class TalkRoomEditRequest {
private Long id;
@Size(min = 1, max = 2000, message = "2000자 이하로 작성해야 합니다.")
private String content;
@NotEmpty(message = "참가 조건은 1개 이상 체크해야합니다.")
private List<String> readingStatus = new ArrayList<>();
...
}
```
프론트단에서 변경된 참가 조건(ReadingStatus)이 `List<String>` 객체로 날라오게 됩니다. 근데 밑에 `Service` 로직을 보시면
```java
@Transactional
public TalkRoomResponse editTalkRoom(TalkRoomEditServiceRequest request, String userEmail) {
User user = userRepository.findByName(userEmail)
.orElseThrow(() -> new BusinessException(ErrorCode.USER_NOT_FOUND));
TalkRoom talkRoom = talkRoomRepository.findById(request.getId())
.orElseThrow(() -> new BusinessException(ErrorCode.TALK_ROOM_NOT_FOUND));
if …
```
=> [Feature] TalkRoom 수정 API 구현

src/main/java/com/jisungin/api/oauth/Auth.java, src/main/java/com/jisungin/api/oauth/AuthArgumentResolver.java, src/main/java/com/jisungin/api/oauth/AuthConstant.java, src/main/java/com/jisungin/api/oauth/AuthContext.java, src/main/java/com/jisungin/api/oauth/AuthInterceptor.java, src/main/java/com/jisungin/api/oauth/OauthController.java, src/main/java/com/jisungin/application/oauth/OauthService.java, src/main/java/com/jisungin/application/talkroom/TalkRoomService.java, src/main/java/com/jisungin/config/AuthConfig.java, src/main/java/com/jisungin/domain/oauth/client/UserClient.java, src/main/java/com/jisungin/domain/oauth/client/UserClientComposite.java, src/main/java/com/jisungin/domain/user/User.java, src/main/java/com/jisungin/exception/ErrorCode.java, src/main/java/com/jisungin/infra/oauth/kakao/KakaoOauthConfig.java, src/main/java/com/jisungin/infra/oauth/kakao/KakaoUserClient.java, src/main/java/com/jisungin/infra/oauth/kakao/client/KakaoApiClient.java
close #12 
- 사용자 식별을 위한 Interceptor, Resolver 구현 
- 카카오 로그아웃 기능 구현
- OAuth 로그아웃 API 추가
구현한 로직의 예는 다음과 같습니다.
1. 프론트단에서 사용자의 세션 ID와 함께 로그아웃 API를 요청한다.
2. Interceptor의 preHandle에서 세션 ID를 꺼내서 AuthContext에 설정한다.
2-1. 만약 세션 ID가 null이라면 예외가 발생한다.
3. Resolver에서 userId(세션 ID)을 `@Auth`에 매핑해서 반환한다.
3-1. 넘어온 userId가 null이라면 예외가 발생한다.
4. 이제 컨트롤러는 `@Auth`에서 userId를 꺼내서 로그아웃 로직을 수행한다.
Interceptor와 Resolver의 자세한 내용은 아래 내용을 참고하시면 좋을 것 같습니다 !
https://tecoble.techcourse.co.kr/post/2021-05-24-spring-interceptor/
코드에서 궁금한 사항이나 의견이 있다면 남겨주세요 ~ 😊
=> [Feature] Spring MVC 인증 기능 구현

.github/workflows/jisungin_dev.yml, Dockerfile, docker-compose.yml, src/test/java/com/jisungin/application/service/book/BookServiceTest.java, src/test/resources/application.yml
close #19 
- `jisungin.co.kr`로 배포 설정 했습니다.
- Dockerfile과 docker-compose.yml을 추가했습니다.
- Github Actions Jobs를 추가했습니다.
커밋 내용에서 질문이나 의견 있으시면 남겨주세요 !
=> [Deploy] `jisungin.co.kr` 배포 설정

src/main/java/com/jisungin/api/book/request/BookCreateRequest.java, src/main/java/com/jisungin/application/book/BookService.java, src/main/java/com/jisungin/application/book/request/BookCreateServiceRequest.java, src/main/java/com/jisungin/application/book/response/BookResponse.java, src/main/java/com/jisungin/application/talkroom/TalkRoomService.java, src/main/java/com/jisungin/domain/book/Book.java, src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImpl.java, src/main/java/com/jisungin/infra/crawler/CrawlingBook.java, src/test/java/com/jisungin/api/book/BookControllerTest.java, src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java, src/test/java/com/jisungin/application/service/talkroom/TalkRoomServiceTest.java, src/test/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImplTest.java
close #22 
- `Book`에 `url` 필드가 `imageUrl` 필드로 변경
- 변경으로 인한 문제 해결
- `Crawler`를 통한 도서 등록 기능 구현
책 등록시 평점은 반드시 `0.0`이게 됩니다. 
그래서 도서 등록시 사용되는 `of(Book book, Double avg)`메서드를  오버라이딩 하여 `of(Book book)` 메서드를 생성했습니다. 그리고 해당 메서드에서 기본 값으로 `0.0`을 설정 해주었습니다. 
```java
public static BookResponse of(Book book) {
return BookResponse.builder()
.title(book.getTitle())
.content(book.getContent())
.authors(book.getAuthors())
.isbn(book.getIsbn())
.publisher(book.getPublisher())
.dateTime(book.getDateTime())
.thumbnail(book.getThumbnail())
.imageUrl(book.getImageUrl())
.ratingAverage(0.0)
.build();
}
```
좀 더 좋은 방식이 있을 것 같은데 좋은 방법이 있을까요?
=> [Refactor] Book 등록 API 수정

src/main/java/com/jisungin/api/comment/CommentController.java, src/main/java/com/jisungin/api/comment/request/CommentCreateRequest.java, src/main/java/com/jisungin/application/comment/CommentService.java, src/main/java/com/jisungin/application/comment/request/CommentCreateServiceRequest.java, src/main/java/com/jisungin/application/comment/response/CommentResponse.java, src/main/java/com/jisungin/domain/comment/Comment.java, src/main/java/com/jisungin/domain/comment/repository/CommentRepository.java, src/test/java/com/jisungin/api/comment/CommentControllerTest.java, src/test/java/com/jisungin/application/comment/CommentServiceTest.java
close #24
* TalkRoom Comment 등록 API 구현
* TalkRoom Comment 등록 API 테스트 코드 작성
이번 코드는 간단하게 등록 API만 작성한거라 리뷰 요구 사항은 없습니다!
=> [Feature] TalkRoom Comment 등록 API 구현

src/test/java/com/jisungin/api/book/BookControllerTest.java, src/test/java/com/jisungin/application/service/book/BookServiceTest.java
close #27 
- #25 에서 발생한 테스트 오류 수정
- API 테스트 `@SpringBootTest`에서 `@WebMvcTest`로 변경
오류 수정 및 어노테이션 변경만 있어 특별한 리뷰 요구 사항은 없습니다!
=> [Test] Book API 테스트 수정

src/main/java/com/jisungin/api/talkroom/TalkRoomController.java, src/main/java/com/jisungin/application/talkroom/TalkRoomService.java, src/main/java/com/jisungin/application/talkroom/response/TalkRoomResponse.java, src/main/java/com/jisungin/domain/talkroom/TalkRoom.java, src/test/java/com/jisungin/ControllerTestSupport.java, src/test/java/com/jisungin/ServiceTestSupport.java, src/test/java/com/jisungin/api/comment/CommentControllerTest.java, src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java, src/test/java/com/jisungin/application/comment/CommentServiceTest.java, src/test/java/com/jisungin/application/service/talkroom/TalkRoomServiceTest.java
close #29 
* API 변경으로 인한 테스트 수정
* API 테스트 통합 클래스 생성
추상클래스 테스트 통합 클래스 적용했습니다!
제 코드 참고하시고 적용하시면 됩니다.
=> [Test] TalkRoom API 테스트 수정

src/main/java/com/jisungin/api/talkroom/TalkRoomController.java, src/main/java/com/jisungin/application/talkroom/TalkRoomService.java, src/main/java/com/jisungin/application/talkroom/response/TalkRoomFindAllResponse.java, src/main/java/com/jisungin/application/talkroom/response/TalkRoomFindOneResponse.java, src/main/java/com/jisungin/application/talkroom/response/TalkRoomQueryComments.java, src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryCustom.java, src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImpl.java, src/test/java/com/jisungin/RepositoryTestSupport.java, src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java, src/test/java/com/jisungin/application/service/talkroom/TalkRoomServiceTest.java, src/test/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImplTest.java
close #33 
* TalkRoom 단건 조회 API 구현
* TalkRoom 단건 조회 API 테스트 코드 작성
1. 먼저 프론트 단에서 넘어온 `TalkRoom_ID` 값을 가지고 해당 `TalkRoom`과 `JOIN`된 `user`, `book` 정보를 가져옵니다.
2. 그 다음으로 해당 ID 값으로 `TalkRoomRole` 과 `JOIN`을 한 `TalkRoom` 정보를 가지고 `TalkRoomRole.Status`을 가지고 옵니다.
3. 두 번째와 마찬가지로 `Comment` 정보도 가져온 뒤 `TalkRoomFindOneResponse`에 넣고 반환해줍니다.
```java
private TalkRoomFindOneResponse findTalkRoomByTalkRoomId(Long talkRoomId) {
return queryFactory.select(new QTalkRoomFindOneResponse(
talkRoom.id.as("talkRoomId"),
user.name.as("userName"),
talkRoom.title,
talkRoom.content,
book.title,
book.imageUrl.as("bookImage")
))
.from(talkRoom)
.join(talkRoom.user, user)
.join(talkRoom.book, book)
.where(talkRoom.id.eq(talkRoomId))
.fetchOne();
}
```
```java
private List<TalkRoomQueryReadingStatus> …
```
=> [Feature] TalkRoom 단건 조회 API 구현

src/main/java/com/jisungin/api/ApiResponse.java, src/main/java/com/jisungin/api/talkroom/TalkRoomController.java, src/main/java/com/jisungin/application/talkroom/TalkRoomService.java, src/main/java/com/jisungin/domain/comment/repository/CommentRepository.java, src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImpl.java, src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java, src/test/java/com/jisungin/application/service/talkroom/TalkRoomServiceTest.java
close #36 
* TalkRoom 삭제 API 구현
* TalkRoom 삭제 API 테스트 코드 작성
1. 프론트 단에서 `TalkRoom_ID`와 `Auth` 정보를 받아온다.
2. `TalkRoom_ID`를 바탕으로 해당 `TalkRoom`을 조회 후 `TalkRoom`을 생성한 `User_ID`와 `Auth_ID` 비교 후 일치하면 `TalkRoom`을 삭제한다.
=> [Feature] TalkRoom 삭제 API 구현

src/main/java/com/jisungin/api/comment/CommentController.java, src/main/java/com/jisungin/api/comment/request/CommentEditRequest.java, src/main/java/com/jisungin/application/comment/CommentService.java, src/main/java/com/jisungin/application/comment/request/CommentEditServiceRequest.java, src/main/java/com/jisungin/application/talkroom/TalkRoomService.java, src/main/java/com/jisungin/domain/comment/Comment.java, src/main/java/com/jisungin/domain/talkroom/TalkRoom.java, src/main/java/com/jisungin/exception/ErrorCode.java, src/test/java/com/jisungin/api/comment/CommentControllerTest.java, src/test/java/com/jisungin/application/comment/CommentServiceTest.java
close #38 
* TalkRoom Comment 수정 API 구현
* TalkRoom Comment 수정 API 테스트 코드 작성
* TalkRoom Comment 삭제 API 구현
* TalkRoom Comment 삭제 API 테스트 코드 작성
간단한 기능 구현이라 리뷰 요구 사항은 생략하도록 하겠습니다!
=> [Feature] TalkRoom Comment 수정, 삭제 API 구현

build.gradle
close #50 
REST Docs 그래들 설정 변경
=> [Setting] REST Docs 그래들 설정 변경

src/main/java/com/jisungin/api/user/UserController.java, src/main/java/com/jisungin/api/user/request/UserRatingGetAllRequest.java, src/main/java/com/jisungin/application/review/response/RatingFindAllResponse.java, src/main/java/com/jisungin/application/user/UserService.java, src/main/java/com/jisungin/application/user/request/UserRatingGetAllServiceRequest.java, src/main/java/com/jisungin/domain/review/RatingOrderType.java, src/main/java/com/jisungin/domain/review/repository/ReviewRepository.java, src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryCustom.java, src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryImpl.java, src/test/java/com/jisungin/ControllerTestSupport.java, src/test/java/com/jisungin/api/user/UserControllerTest.java, src/test/java/com/jisungin/application/user/UserServiceTest.java, src/test/java/com/jisungin/domain/review/repository/ReviewRepositoryTest.java
close #43 
- 사용자 별점 조회 API 추가
- 페이징 구현
- 정렬 기준 (등록시간, 별점 오름차/내림차, 평균 별점 오름차/내림차)
- 별점 선택 (`etc` 2.0, 3.5, 5.0)
```java
@Override
public PageResponse<RatingFindAllResponse> findAllRatingOrderBy(
Long userId, RatingOrderType ratingSortType, Double rating, int size, int offset) {
log.info("--------------start--------------");
// 리뷰 조회, 쿼리 1회
List<RatingFindAllResponse> ratings = getRatings(userId, ratingSortType, rating, size, offset);
return PageResponse.<RatingFindAllResponse>builder()
.queryResponse(ratings)
.totalCount(getTotalCount(userId, rating)) // 해당 유저의 리뷰 총 개수, 쿼리 1회
.size(size)
.build();
}
// ... 중간 생략 ...
private OrderSpecifier createSpecifier(RatingOrderType ratingSortType) {
if (ratingSortType.equals(RATING_ASC)) {
return review.rating.asc();
}
if …
```
=> [Feature] 사용자 별점 조회 API 구현

src/main/java/com/jisungin/api/search/SearchController.java, src/main/java/com/jisungin/api/search/request/SearchKeywordRequest.java, src/main/java/com/jisungin/application/search/SearchService.java, src/main/java/com/jisungin/config/RedisConfig.java, src/test/java/com/jisungin/ControllerTestSupport.java, src/test/java/com/jisungin/api/search/SearchControllerTest.java, src/test/java/com/jisungin/application/search/SearchServiceTest.java
close #67 
- Redis Sorted Set으로 실시간 검색어 기능 구현
현재는 검색어에 점수를 부여하여 조회하는 기능입니다.
궁금한 점이나 의견 있으면 남겨주세요 ! 😊
=> [Feature] 실시간 검색어 API 구현

src/main/java/com/jisungin/api/oauth/AuthInterceptor.java, src/main/java/com/jisungin/api/oauth/OauthController.java, src/main/java/com/jisungin/config/WebConfig.java, src/main/resources/application.yml
close #78 
- 프론트 요청 허용 주소를 기존 로컬 주소에서 `https://api.jisungin.co.kr`로 수정했습니다.
=> [Deploy] 프론트 연동을 위한 코드 수정

src/main/java/com/jisungin/api/comment/CommentController.java, src/main/java/com/jisungin/api/oauth/AuthInterceptor.java, src/main/java/com/jisungin/config/AuthConfig.java, src/test/java/com/jisungin/ControllerTestSupport.java, src/test/java/com/jisungin/api/comment/CommentControllerTest.java, src/test/java/com/jisungin/api/commentlike/CommentLikeControllerTest.java, src/test/java/com/jisungin/api/review/ReviewControllerTest.java, src/test/java/com/jisungin/api/reviewlike/ReviewLikeControllerTest.java, src/test/java/com/jisungin/api/talkroom/TalkRoomControllerTest.java, src/test/java/com/jisungin/api/talkroomlike/TalkRoomLikeControllerTest.java, src/test/java/com/jisungin/api/user/UserControllerTest.java, src/test/java/com/jisungin/api/userlibrary/UserLibraryControllerTest.java
close #96 
* 로그인 시 유저 ID값을 받도록 수정
```java
public void addInterceptors(InterceptorRegistry registry) {
registry.addInterceptor(authInterceptor)
.addPathPatterns(
"/v1/oauth/logout/**"
"/v1/{talkRoom}/comments/**",
"/v1/comments/**",
"/v1/{commentId}/likes/**",
"/v1/logout/**",
"/v1/reviews/**",
"/v1/talk-rooms/**",
"/v1/users/**",
"/v1/user-libraries/**"
);
```
여기에  URL을 설정해서 해결했습니다.
그리고 현재 Controller 테스트에서 세션 설정이 안돼서 일단은 주석처리로 했습니다. 추후에 같이 이야기 나누면서 어떻게 해결해야할지 고민해봅시다!!
=> [BugFix] 로그인 시 유저 ID값을 받도록 수정

src/docs/asciidoc/api/rating/rating.adoc, src/docs/asciidoc/api/review/review.adoc, src/docs/asciidoc/api/user/user.adoc, src/docs/asciidoc/index.adoc, src/main/java/com/jisungin/api/rating/RatingController.java, src/main/java/com/jisungin/api/review/ReviewController.java, src/main/java/com/jisungin/api/user/UserController.java, src/main/java/com/jisungin/application/rating/RatingService.java, src/main/java/com/jisungin/application/rating/response/RatingCreateResponse.java, src/main/java/com/jisungin/application/rating/response/RatingGetOneResponse.java, src/main/java/com/jisungin/application/user/UserService.java, src/main/java/com/jisungin/application/user/response/UserInfoResponse.java, src/main/java/com/jisungin/config/SecurityConfig.java, src/main/java/com/jisungin/domain/rating/repository/RatingRepository.java, src/main/java/com/jisungin/exception/ErrorCode.java, src/test/java/com/jisungin/api/user/UserControllerTest.java, src/test/java/com/jisungin/application/rating/RatingServiceTest.java, src/test/java/com/jisungin/application/user/UserServiceTest.java, src/test/java/com/jisungin/docs/rating/RatingControllerDocsTest.java, src/test/java/com/jisungin/docs/review/ReviewControllerDocsTest.java, src/test/java/com/jisungin/docs/user/UserControllerDocsTest.java
close #101 
- 별점 생성, 삭제, 페이지 조회
- 한줄평 생성, 삭제, 페이지 조회
- 유저 상세 조회
- 별점 수정, 단일 조회 API 추가
해당 API 추가하고 REST Docs도 작성했습니다.
궁금한 점 있으시면 코멘트 남겨주세요 !
=> [Docs] 마이페이지 API REST Docs 작성

src/docs/asciidoc/api/review/review.adoc, src/main/java/com/jisungin/api/review/ReviewController.java, src/main/java/com/jisungin/application/OffsetLimit.java, src/main/java/com/jisungin/application/SliceResponse.java, src/main/java/com/jisungin/application/review/ReviewService.java, src/main/java/com/jisungin/application/review/response/ReviewWithRatingResponse.java, src/main/java/com/jisungin/domain/review/ReviewOrderType.java, src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryCustom.java, src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryImpl.java, src/test/java/com/jisungin/api/review/ReviewControllerTest.java, src/test/java/com/jisungin/application/review/ReviewServiceTest.java, src/test/java/com/jisungin/docs/review/ReviewControllerDocsTest.java, src/test/java/com/jisungin/domain/review/repository/ReviewRepositoryTest.java
close #90 
이번 PR에서 작업한 내용을 간략히 설명해주세요.
- 도서와 관련된 리뷰 조회 API 구현
- 도서와 관련된 리뷰 조회 API 테스트 작성
- 도서와 관련된 리뷰 조회 API Docs 작성
=> [Feature] 도서와 관련된 리뷰 조회 API 구현

src/docs/asciidoc/api/userlibrary/userlibrary.adoc, src/main/java/com/jisungin/application/rating/RatingService.java, src/main/java/com/jisungin/application/review/response/ReviewContentResponse.java, src/main/java/com/jisungin/application/userlibrary/response/UserReadingStatusResponse.java, src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryImpl.java, src/main/java/com/jisungin/domain/userlibrary/repository/UserLibraryRepositoryImpl.java, src/test/java/com/jisungin/application/rating/RatingServiceTest.java, src/test/java/com/jisungin/docs/user/UserControllerDocsTest.java
close #108 
- 별점 단일 조회 시, 결과가 없을 경우 빈 값을 전달하도록 수정
- 독서 상태 페이지 조회 REST Docs 추가
특별히 없습니다 ~ 😊
=> [Feature] 한줄평 관련 API 수정, 독서 상태 REST Docs 추가

src/main/java/com/jisungin/application/comment/CommentFindAllResponse.java, src/main/java/com/jisungin/application/comment/CommentService.java, src/test/java/com/jisungin/application/comment/CommentServiceTest.java
close #117 
Comment 조회 시 이미지가 없다면 null 반환 하도록 수정
=> [Refactor] Comment 조회 시 이미지가 없다면 null 반환 하도록 수정

src/main/java/com/jisungin/application/review/response/ReviewContentResponse.java, src/main/java/com/jisungin/domain/review/repository/ReviewRepositoryImpl.java, src/test/java/com/jisungin/api/user/UserControllerTest.java, src/test/java/com/jisungin/application/user/UserServiceTest.java, src/test/java/com/jisungin/docs/user/UserControllerDocsTest.java, src/test/java/com/jisungin/domain/review/repository/ReviewRepositoryTest.java
close #120 
- 한줄평 페이지 조회 API의 별점 평균 정렬 방식을 수정
- 페이지 조회 시, 각 엔티티마다 총 좋아요 개수 필드 추가
특별히 없습니다 ~
=> [Refactor] 한줄평 페이지 조회 API의 별점 평균 정렬 방식 수정

src/main/java/com/jisungin/api/talkroom/TalkRoomController.java, src/main/java/com/jisungin/application/SliceResponse.java, src/main/java/com/jisungin/application/book/response/BookRelatedTalkRoomResponse.java, src/main/java/com/jisungin/application/talkroom/TalkRoomService.java, src/main/java/com/jisungin/application/talkroom/request/TalkRoomSearchCondition.java, src/main/java/com/jisungin/application/talkroom/request/UserTalkRoomSearchCondition.java, src/main/java/com/jisungin/application/talkroom/response/TalkRoomFindAllResponse.java, src/main/java/com/jisungin/application/talkroom/response/TalkRoomFindOneResponse.java, src/main/java/com/jisungin/application/talkroom/response/TalkRoomQueryEntity.java, src/main/java/com/jisungin/application/talkroom/response/TalkRoomRelatedBookResponse.java, src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomOrderType.java, src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryCustom.java, src/main/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryImpl.java, src/test/java/com/jisungin/application/talkroom/TalkRoomServiceTest.java, src/test/java/com/jisungin/docs/talkroom/TalkRoomControllerDocsTest.java, src/test/java/com/jisungin/domain/talkroom/repository/TalkRoomRepositoryTest.java
close #124 
- 토크룸 목록 조회 API Slice로 리턴하도록 수정
- 토크룸 조회 조건 리팩토링
- 사용자 토크룸 조회 조건 리팩토링
=> [Refactor] 토크룸 목록 조회 API Slice로 리턴하도록 수정

.github/workflows/pr_test.yml, .github/workflows/pr_text.yml, build.gradle, lombok.config
close #126 
- 테스트 커버리지 분석 도구, JaCoCo를 적용했습니다.
- 테스트 커버리지 참고해주세요. 😄
- [관련 내용](https://trysolve.tistory.com/37)을 정리했는데 한 번 확인해보시면 좋을 것 같아요 ~
=> [Deploy] JaCoCo 테스트 커버리지 분석 적용
